#!/usr/bin/perl
#
# 
# Hello world example
#
# ./generate.pl <problem_text> <solution_text>
#

($problem_file, $solution_file) = @ARGV;

# word list from jargon.txt of hacker terms, and some
@words = ("a", "A", "ADM", "ADVENT", "AI", "AND", "ANGLE", "AOS", "AP", "ARG", "AROUND", "ARPAnet", "ASCII", "AT", 
"AUTOMAGICALLY", "Abbreviated", "Abbreviation", "Able", "Accumulator", "Actually", "Adventure", "Aesthetically", 
"Agre", "Aha", "Alan", "All", "Also", "Alternate", "Although", "American", "An", "Anglicized", "Anglo", "Another", 
"Any", "Anyone", "Anything", "Anywhere", "Aos", "Are", "Arthur", "As", "Assorted", "At", "Automatically", "B", 
"BAGBITER", "BAGBITING", "BANG", "BAR", "BARF", "BARFUCIOUS", "BARFULOUS", "BAZ", "BBN", "BCNU", "BEEP", "BEGIN", 
"BELLS", "BIG", "BIGNUM", "BIGNUMS", "BIN", "BINARY", "BIT", "BITBLT", "BITS", "BLEEP", "BLETCH", "BLETCHEROUS", "BLT", 
"BMW", "BOGOSITY", "BOGUS", "BOUNCE", "BRACKETS", "BRAIN", "BREAK", "BREAKPOINT", "BREEDLE", "BRING", "BROKEN", 
"BROKET", "BTW", "BUCKET", "BUCKY", "BUG", "BUM", "BUZZ", "BYE", "Badly", "Basically", "Be", "Becoming", "Begin", 
"Behaving", "Being", "Beyond", "Bignum", "Bill", "Bits", "Bob", "Bogus", "Boolean", "Boston", "Bounce", "Bowl", "Boy", 
"Brain", "Brown", "Bucky", "By", "C", "CAMINO", "CANONICAL", "CATATONIA", "CATATONIC", "CDR", "CHANGE", "CHINE", 
"CHOMP", "CHOMPER", "CHOMPING", "CLOSE", "CLOVER", "CMU", "COBOL", "COKEBOTTLE", "COLLECT", "COLLECTION", "COM", 
"COMM", "COMPILER", "CONNECTOR", "CONS", "CONSPIRACY", "CONTEXT", "COrrector", "CPU", "CR", "CRASH", "CRETIN", 
"CRETINOUS", "CRLF", "CROCK", "CRUFT", "CRUFTIE", "CRUFTY", "CRUNCH", "CS", "CSP", "CTRL", "CTSS", "CTY", "CUL", 
"CUSP", "CUSPY", "Calling", "Caltech", "Camino", "Can", "Canonical", "Cheatham", "Chevy", "Chinatown", "Chinese", 
"Choke", "Chomp", "City", "Clarke", "Close", "Club", "Cockney", "Com", "Commands", "Common", "Commonly", "Compare", 
"Condition", "Congenital", "Connotes", "Consisting", "Conway", "Craig", "Cruft", "Crunchly", "DAEMON", "DAMAGED", 
"DAY", "DDT", "DEADLOCK", "DEADLOCKED", "DEADLY", "DEC", "DECtape", "defcon", "DEF CON", "DEFCON", "DEFUN", "DEMENTED", 
"DEMON", "DESERVE", "DIABLO", "DIDDLE", "DIKE", "DM", "DMP", "DMS", "DO", "DOUBLE", "DOWN", "DPB", "DPL", "DRAGON", 
"DSK", "DTRT", "DUPer", "DWIM", "Daemons", "Damage", "Dave", "David", "Decoding", "Definitions", "Demons", "Derived", 
"Deserving", "Diablo", "Dick", "Dictionary", "Disgusting", "Do", "Dobb", "Does", "Double", "Doubling", "Down", "Dr", 
"Drop", "Dungeon", "E", "EASY", "EL", "EMBRACE", "END", "ENGLISH", "EPSILON", "EQUALS", "ERROR", "EXCH", "EXCL", "EXE", 
"EXecutive", "Earnest", "East", "Eating", "Editor", "Einstein", "Either", "El", "Emphatic", "End", "English", 
"Entered", "Enterprise", "Equipment", "Ergo", "Eric", "Especially", "Etymological", "Europe", "Everhart", "Example", 
"Examples", "Except", "Exclusive", "Extreme", "Extremely", "F", "FACTOR", "FAULTY", "FEATURE", "FEED", "FEEP", 
"FENCEPOST", "FFT", "FILE", "FILES", "FIND", "FINE", "FISH", "FLAG", "FLAKEY", "FLAME", "FLAP", "FLAVOR", "FLAVORFUL", 
"FLUSH", "FOBY", "FOO", "FOOBAR", "FORTRAN", "FRG", "FRIED", "FROB", "FROBBOTZIM", "FROBBOZ", "FROBNICATE", "FROBNITZ", 
"FROBNITZEM", "FROBNODULE", "FROBNULE", "FROBULE", "FROG", "FROGGY", "FROTZ", "FRY", "FTP", "FUBAR", "FUDGE", "FYI", 
"Fabritek", "Failing", "False", "February", "File", "Finally", "Flame", "Foodp", "For", "Force", "Francisco", 
"Frankston", "Fred", "Friday", "Frivolous", "Frob", "From", "Fucked", "Functionally", "GA", "GABRIEL", "GARBAGE", 
"GARPLY", "GAS", "GASEOUS", "GC", "GEDANKEN", "GLASS", "GLITCH", "GLORK", "GLS", "GOBBLE", "GORP", "GREAT", "GRIND", 
"GRITCH", "GROK", "GRONK", "GRONKED", "GROVEL", "GRUNGY", "GUBBISH", "GUN", "Gabriel", "Garbage", "Gardner", "Gas", 
"Generally", "Geoff", "German", "Get", "Give", "Glitch", "Glob", "Globe", "Go", "Goldberg", "Good", "Goodfellow", 
"Gosling", "Gosper", "Gosperism", "Grammatically", "Graphics", "Gratuitously", "Great", "Greenblatt", "Gritch", "Guy", 
"H", "HACK", "HACKER", "HACKING", "HACKISH", "HACKISHNESS", "HAIR", "HAIRY", "HAKMEM", "HANDWAVE", "HAPPY", "HARD", 
"HARDWARILY", "HASH", "HBD", "HELLO", "HELLOP", "HIRSUTE", "HOOK", "HOW", "HUMONGOUS", "HUMUNGOUS", "HUNGUS", "HYPER", 
"Hacker", "Hacks", "Hall", "Hard", "Harried", "Hart", "Harvard", "Has", "He", "Heights", "Heinlein", "Hence", "Herald", 
"His", "Historical", "Honeywell", "Horrid", "Horton", "Huffman", "Human", "Humorous", "Hypothetical", "I", "IBM", 
"IFS", "IMPCOM", "IN", "INFINITE", "INFINITY", "INTERLISP", "IRI", "IRP", "IT", "ITS", "Identified", "If", "In", 
"Incoherent", "Incomprehensible", "Incorrect", "Incredibly", "Indeterminate", "Interval", "Invented", "Inverse", "It", 
"J", "JFCL", "JIFFY", "JOCK", "JRST", "JSI", "JSR", "JSYS", "Jack", "Jacks", "Jake", "James", "Jean", "John", "Johnny", 
"Jose", "Journal", "Jr", "Jump", "June", "Just", "K", "KA", "KL", "KLUDGE", "KLUGE", "Kazar", "Knight", "Krux", "L", 
"LDB", "LEDs", "LEFT", "LESSER", "LF", "LIFE", "LIFO", "LINE", "LINK", "LISP", "LOADER", "LOGICAL", "LOSE", "LOSER", 
"LOSING", "LOSS", "LOSSAGE", "LOTS", "LOW", "LPT", "LSH", "LUSER", "Lab", "Land", "Large", "Latin", "Lebling", 
"Lehman", "Lemme", "Les", "Let", "Lewis", "Like", "Line", "Lisp", "LispMachine", "List", "Littleboy", "Lose", "Loser", 
"Louie", "MACROTAPE", "MAGIC", "MARGINAL", "MARGINALLY", "MAZES", "MC", "MEDIOCRE", "MESH", "META", "MICRO", 
"MICROTAPE", "MIDAS", "MINUS", "MISFEATURE", "MIT", "MOBY", "MODE", "MODERATELY", "MODULO", "MOO", "MOON", "MRC", 
"MULTICS", "MUMBLAGE", "MUMBLE", "MUNCH", "MUNCHING", "MUNG", "MUNGE", "MacLISP", "Machine", "Macsyma", "Manual", 
"Many", "Margaret", "Marginal", "Martian", "Martin", "Marvel", "Matter", "Maximally", "May", "Mean", "Meanwhile", 
"Melville", "Memo", "Mexico", "Michael", "Mike", "Moby", "Model", "Moon", "More", "Most", "Mostly", "MtFBWY", "Much", 
"Muggs", "Multics", "Multiple", "Mumble", "Mung", "My", "Mythical", "Mythically", "N", "NAME", "NEAT", "NEWIO", 
"NIGHT", "NIL", "NOT", "NTH", "NUAL", "NUL", "NUMBER", "Name", "Never", "New", "News", "Niklaus", "No", "Nobody", 
"Non", "Not", "Note", "Noted", "Now", "Nth", "Number", "Nurd", "O", "OBSCENELY", "OBSCURE", "OBTW", "OF", "ON", 
"OPCON", "OPEN", "OR", "ORDER", "OUT", "Obviously", "Occasional", "Occasionally", "October", "Of", "Often", "Oh", 
"Old", "On", "One", "Open", "Operation", "Ordinary", "Original", "Originally", "Other", "Over", "Overly", "P", "PAPER", 
"PARSE", "PATCH", "PDL", "PDP", "PEN", "PERFECTION", "PESSIMAL", "PESSIMIZING", "PHANTOM", "PHASE", "PHOTO", "PHROG", 
"PHW", "PIG", "PLUGH", "PLUS", "PM", "POM", "POP", "POPJ", "POUND", "PPN", "PRETTY", "PRINT", "PROTOCOL", 
"PSEUDOPRIME", "PTY", "PTYJOB", "PTYs", "PUNT", "PUSH", "PUSHJ", "Peanuts", "Peculiar", "People", "Performing", 
"Phase", "Pickle", "Place", "Pogo", "Polymorphic", "Poor", "Poorly", "Popj", "Precision", "Predicate", "Prefix", 
"Princeton", "Printer", "Probably", "Program", "Programmer", "Programming", "Project", "Protocol", "Pseudo", "Punkab", 
"Push", "QUES", "QUUCES", "QUUX", "QUUXANDUM", "QUUXARE", "QUUXES", "QUUXO", "QUUXU", "QUUXUUM", "QUUXY", "Quite", 
"Quux", "R", "RAG", "RANDOM", "RANDOMNESS", "RAPE", "RAVE", "REAL", "RECURSION", "REL", "RF", "RIGHT", "ROT", "RPG", 
"RUDE", "Railroad", "Raisins", "Random", "Rarely", "Raymond", "Real", "Recognition", "Refers", "Reid", "Related", 
"Release", "Reserved", "Right", "Robert", "Rose", "Rube", "Rumor", "S", "SACRED", "SAGA", "SAIL", "SAV", "SCREW", 
"SCRIBE", "SD", "SEC", "SEMI", "SERVER", "SF", "SHARP", "SHIANG", "SHIFT", "SHR", "SHRIEK", "SIGN", "SINCE", "SLOP", 
"SLURP", "SMART", "SMOKING", "SMOP", "SNAME", "SNARF", "SOCCER", "SOFTWARE", "SOFTWARILY", "SON", "SOS", "SPAZZ", 
"SPLAT", "SQUARES", "SRI", "STARVE", "STATE", "STINK", "STOPGAP", "STOPPAGE", "STY", "SUITABLE", "SUPDUP", "SUPER", 
"SUPERPROGRAMMER", "SUPer", "SWAPPED", "SYS", "SYSBIN", "SYSENG", "SYSTEM", "SYStem", "Said", "Sam", "Same", "Sammet", 
"San", "Sandwich", "Saxon", "School", "Scientific", "See", "Semi", "Serendipity", "Shall", "Shamos", "Should", 
"Shuffling", "Silly", "Similar", "Simple", "Since", "Sjoberg", "Slightly", "Slime", "Small", "Smokey", "Snoopy", "So", 
"Some", "Someone", "Something", "Sometimes", "Sorry", "Soundalike", "Split", "Spoken", "Stallman", "Standard", 
"Stanford", "Star", "Starting", "State", "States", "Steele", "Stop", "Stover", "Straight", "Strange", "Stranger", 
"Subject", "Suppose", "Sussman", "Swapping", "Swide", "Synonyms", "System", "Systems", "T", "TAIL", "TAKE", "TALK", 
"TASTE", "TASTEFUL", "TASTEFULNESS", "TASTY", "TCP", "TECO", "TELNET", "TEN", "TENEX", "TENSE", "TERPRI", "THE", 
"THEORY", "THERE", "THING", "THRASH", "TICK", "TIME", "TN", "TNX", "TO", "TOOL", "TOPS", "TRAP", "TRIANGLES", "TTY", 
"TV", "TWEAK", "TWENEX", "TWIDDLE", "Tech", "Tends", "Tenex", "Tenices", "Term", "Terminal", "Text", "Thanks", "That", 
"The", "There", "These", "They", "Thing", "This", "Those", "Three", "Thus", "Time", "Times", "To", "Tom", "Torch", 
"Transfer", "Twenex", "Twiddling", "Typical", "Typically", "U", "UNAME", "UNIX", "UP", "USER", "UUO", "Un", 
"Understood", "Unfortunately", "Unimplemented", "United", "University", "Unnecessary", "Unpleasant", "Unpredictable", 
"Until", "Unused", "Up", "Upon", "Usage", "Use", "Used", "Useless", "User", "Using", "Usually", "VALUE", "VANILLA", 
"VAX", "VAXEN", "VIRGIN", "VIRTUAL", "VISIONARY", "VT", "Variant", "Variety", "Verb", "Very", "Virtual", "W", "WALBEG", 
"WALDO", "WALEND", "WALL", "WALLPAPER", "WARS", "WATERBOTTLE", "WAY", "WEDGED", "WHAT", "WHEEL", "WHISTLES", "WHOLE", 
"WIN", "WINNAGE", "WINNER", "WINNITUDE", "WITHIN", "WIZARD", "WORLD", "WORMHOLE", "WOW", "WPI", "WWII", "Wait", 
"Waldo", "Wall", "Wars", "Watcha", "We", "Well", "West", "What", "When", "Whenever", "Which", "Who", "Why", "Wirth", 
"With", "Words", "Working", "World", "Wuthering", "X", "XCT", "XGP", "XOR", "XYZZY", "Xerox", "YOYO", "YU", "Yale", 
"Yeah", "Yes", "Yet", "Yiddish", "York", "You", "Your", "Yourdon", "ZERO", "Zork", "a", "abbreviated", 
"abbreviation", "able", "aborting", "about", "above", "absolute", "absolutely", "ac", "acceptable", "acceptably", 
"access", "accessible", "accidental", "accidentally", "accompanied", "accompanies", "accomplish", "accomplished", 
"accomplishing", "according", "accounting", "accounts", "accumulates", "accumulator", "acronym", "act", "action", 
"actions", "activate", "activities", "activity", "acts", "actual", "actually", "ad", "adapted", "add", "added", 
"adding", "addition", "additional", "additions", "address", "addressable", "addresses", "adds", "adequate", "adj", 
"adjective", "adjunct", "adjust", "adjusting", "administrative", "admiration", "adv", "advantage", "aesthetic", 
"affectionate", "afraid", "after", "again", "against", "agenda", "ago", "agree", "agreed", "agrees", "ah", "ahead", 
"ahs", "aimless", "algorithm", "alive", "all", "allowed", "allowing", "allows", "alma", "almost", "alone", "along", 
"aloud", "also", "alt", "alternate", "alternates", "alternative", "alternatively", "although", "altmode", "alumni", 
"alumnus", "always", "amazing", "ambiguity", "ambiguous", "among", "amount", "amounts", "amusing", "an", "analogy", 
"ancient", "and", "animation", "annoy", "annoyance", "annoying", "annul", "another", "answer", "anti", "anticipated", 
"antiquated", "antonym", "antonyms", "any", "anyone", "anything", "anyway", "aos", "apart", "apparent", "apparently", 
"appearance", "appears", "appended", "appending", "applications", "applied", "apply", "applying", "appreciating", 
"appropriate", "approve", "approximately", "arbitrarily", "arbitrary", "archaic", "are", "area", "aren", "argument", 
"arguments", "arise", "arm", "around", "articulation", "as", "ask", "asked", "asking", "asks", "asleep", "aspects", 
"ass", "assembler", "assembly", "associated", "assorted", "assume", "assumed", "assumptions", "astronomical", "at", 
"atmosphere", "attack", "attacked", "attained", "attempt", "attempting", "attempts", "attitude", "attribute", "aus", 
"author", "authoritative", "authoritatively", "autobogophobia", "automagically", "automata", "automatically", 
"availability", "available", "average", "avoid", "awake", "aware", "away", "awkward", "axe", "ay", "back", 
"backgammon", "background", "backward", "bacon", "bad", "bag", "bagbiter", "bagbiting", "bahz", "banging", "barf", 
"barfs", "based", "basic", "basis", "be", "bear", "beat", "because", "become", "becomes", "becoming", "been", "beep", 
"before", "began", "begin", "beginning", "behave", "behaves", "behaving", "behind", "being", "believe", "bell", 
"bells", "belonging", "beloved", "belt", "best", "better", "between", "bgcolor", "big", "bill", "binaries", "binary", 
"bit", "biting", "bitmapped", "bits", "bitten", "black", "blamed", "blank", "blatantly", "blather", "bleepers", 
"bletcherous", "blit", "blithely", "blobby", "block", "blow", "body", "bogometer", "bogosity", "bogotified", "bogus", 
"bones", "bony", "book", "boot", "both", "bounce", "boundary", "bowl", "bowling", "boxes", "bracket", "brain", "break", 
"brechen", "brilliant", "bring", "broke", "broken", "brothers", "brought", "brute", "bucky", "buffer", "buffers", 
"bug", "bugs", "build", "built", "bullshitting", "bum", "bummed", "bunch", "burn", "burnt", "business", "but", 
"butted", "butter", "buy", "by", "byte", "cabinet", "cable", "calculate", "call", "called", "calling", "calls", "came", 
"campfire", "campus", "can", "cancel", "candle", "canonical", "canonically", "capabilities", "capable", "car", "card", 
"career", "carefully", "carriage", "carried", "cars", "cartoon", "cartoons", "case", "cases", "catching", "category", 
"catsup", "cause", "caused", "causes", "causing", "cdr", "cease", "cedes", "celebrated", "celestial", "cellular", 
"certain", "certainly", "chains", "chair", "chamber", "change", "changed", "changes", "changing", "channel", 
"channels", "character", "characterized", "characters", "check", "chew", "chomp", "chosen", "christened", "chuh", 
"circa", "circle", "circumstances", "city", "claim", "clarity", "class", "classes", "clean", "cleaner", "clear", 
"clearly", "clever", "cleverness", "clobbering", "clock", "close", "closest", "coarse", "coast", "code", "coded", 
"codes", "coefficients", "coffee", "coincidences", "cokebottle", "collapse", "collection", "colon", "color", "com", 
"combination", "come", "comes", "comic", "comics", "coming", "command", "commands", "comment", "comments", 
"commercial", "commit", "common", "commonly", "communicate", "communicating", "community", "compared", "compares", 
"comparison", "compass", "compatible", "compete", "competent", "compiled", "compiler", "complain", "complaint", 
"completely", "completeness", "completes", "complex", "complexity", "complicated", "complications", "comprehend", 
"comprehensibility", "compression", "computation", "computations", "computer", "computers", "computes", "computing", 
"concept", "concerning", "condition", "conditions", "conference", "configurations", "confirm", "confused", "confusing", 
"confusion", "congregate", "conjunction", "connectors", "connects", "connotation", "connotations", "connote", 
"connotes", "cons", "conscience", "consecutive", "consed", "consequences", "consider", "considered", "consisting", 
"console", "constipation", "constitute", "constraint", "construction", "consume", "consumes", "consuming", 
"containing", "contains", "context", "contiguous", "continue", "continues", "continuum", "contributed", "control", 
"controlled", "controlling", "controversy", "convention", "conversation", "coordinate", "coordinates", "copied", 
"copy", "core", "correct", "corrected", "correcting", "correctly", "correlated", "corresponding", "corruption", "cost", 
"costly", "could", "counterpart", "counting", "couple", "course", "court", "cover", "craft", "crap", "crapped", 
"crash", "crashed", "crashes", "create", "creating", "creaturism", "creeping", "cretinisms", "cretinous", "cringe", 
"criteria", "crock", "crocks", "cruddy", "cruft", "crufties", "crufty", "crul", "crunch", "crunched", "crunching", 
"cul", "cultural", "culture", "cur", "current", "cursor", "cuspy", "cutters", "cycle", "cycles", "daemon", "daemons", 
"damage", "damaged", "data", "dating", "day", "days", "deactivate", "deadlock", "deadly", "dealing", "deboned", 
"debug", "debugging", "decay", "deceased", "decide", "decided", "decimal", "decision", "decisions", "decrease", 
"deduced", "dee", "def", "default", "defaulting", "defies", "defined", "definition", "degree", "delete", "deleted", 
"deliberately", "demented", "demon", "demons", "denotation", "denote", "denotes", "denying", "department", "depend", 
"dependent", "depending", "depends", "deponent", "depression", "der", "derived", "derives", "describe", "described", 
"describing", "deserves", "design", "designed", "desired", "desk", "destination", "destroy", "destroyed", "detail", 
"details", "determine", "deterministic", "developed", "device", "devices", "diagonal", "dialect", "dialects", "dib", 
"dice", "did", "diddle", "diddled", "didn", "difference", "different", "difficult", "difficulty", "digression", "dike", 
"dinner", "dinnertime", "direction", "directions", "directories", "directory", "dirty", "disable", "disagree", 
"disagreement", "disc", "discard", "discourage", "discover", "discovered", "discrete", "discussing", "discussion", 
"disease", "disgust", "disgusting", "disgustitude", "disk", "disks", "dispensed", "display", "displayed", 
"distasteful", "distinct", "distinction", "distinctly", "distinguish", "distinguishes", "distract", "disturbed", "dja", 
"djif", "do", "docu", "document", "documentation", "documenting", "does", "doesn", "doing", "don", "done", "dormant", 
"double", "doubled", "doubles", "doubling", "doubly", "doubt", "down", "downright", "drastic", "drastically", "dress", 
"dried", "drifted", "driver", "drives", "dropping", "due", "duh", "dump", "duplicate", "duplicity", "during", "e", 
"each", "early", "easier", "easily", "easy", "echoed", "echoing", "ed", "edit", "editing", "editor", "editors", "ee", 
"effects", "efficient", "effort", "efforts", "eight", "either", "eks", "ekstch", "ekx", "elaborate", "elbows", 
"electric", "electronic", "element", "elements", "elicit", "eliminate", "else", "elsewhere", "emergency", 
"emotionally", "emphasis", "emphatic", "employs", "encounters", "encrusted", "end", "ended", "endings", "ends", 
"engineers", "enjoys", "enough", "entails", "enter", "entered", "enthusiastically", "entirely", "entry", "enunciate", 
"epsilon", "equation", "equivalent", "erase", "erp", "erratically", "error", "errors", "escalator", "esp", 
"especially", "ess", "essentially", "etc", "evangelize", "even", "events", "eventually", "ever", "every", "everybody", 
"everything", "evidenced", "evident", "evolved", "ex", "exactly", "exaggeration", "examined", "example", "examples", 
"excellent", "except", "exceptional", "exceptionally", "exchange", "exclamation", "exclude", "exclusive", "excuse", 
"execute", "exhausted", "exhibited", "exhibiting", "exist", "existence", "existing", "expect", "expending", "expense", 
"expensive", "experimenten", "expert", "explain", "explaining", "explanation", "explication", "explicit", "explicitly", 
"exposure", "expressed", "expression", "extendable", "extended", "extending", "extension", "extent", "exterminating", 
"extra", "extract", "extracting", "extraneous", "extreme", "extremely", "eyes", "facility", "fact", "factor", 
"faculty", "fail", "fails", "failure", "failures", "fairly", "fake", "false", "family", "fanatic", "fans", "far", 
"farewell", "fashion", "fast", "faulty", "favorite", "fear", "feat", "feature", "features", "featurism", "feed", 
"feel", "feeling", "feep", "feeper", "feeping", "feeps", "feet", "feh", "fellow", "fence", "fencepost", "ferocity", 
"ferrous", "few", "ffffff", "field", "figured", "fik", "file", "files", "filtered", "finally", "find", "finds", "fine", 
"fingers", "finish", "finished", "first", "fish", "fit", "fittip", "fix", "fixed", "fixes", "fixing", "fixnums", 
"flag", "flakey", "flame", "flap", "flavor", "flavored", "flavors", "flonums", "flush", "flushed", "flutter", 
"followed", "following", "follows", "foo", "food", "fooey", "for", "forbidden", "force", "forcibly", "forearms", 
"forever", "forget", "form", "format", "former", "formerly", "forms", "forward", "found", "four", "freaks", "free", 
"frequent", "frequently", "fried", "friendliness", "friendly", "frob", "frobbing", "froggy", "from", "fruh", "fudge", 
"fudged", "full", "fun", "function", "functional", "functioning", "functions", "furniture", "further", "future", "g", 
"game", "gamma", "garbage", "gas", "gassed", "gears", "gedanken", "general", "generalization", "generally", "generate", 
"generated", "generates", "generic", "generosity", "generous", "genitive", "gesture", "gestures", "get", "getting", 
"ghis", "giggle", "give", "given", "glass", "glims", "glitch", "glitshen", "global", "glorked", "glory", "gloss", 
"glossary", "gnashing", "go", "goal", "gobble", "gobbles", "goes", "going", "gone", "good", "got", "government", 
"grab", "grabbed", "grabs", "grad", "grade", "graduate", "grand", "gratuitous", "gratuitously", "great", "greater", 
"greeting", "gritch", "groan", "gronk", "gronked", "gross", "group", "grovelled", "growing", "grubby", "grungy", "gt", 
"guarantee", "gubbish", "guess", "gul", "gun", "gunned", "hack", "hacked", "hacker", "hackers", "hackification", 
"hacking", "hacks", "hair", "hairy", "half", "halfway", "hand", "handler", "handles", "hands", "handwave", "handwaved", 
"handwaving", "happen", "happens", "hardware", "hardwarily", "hardwary", "harmlessness", "has", "hatred", "have", 
"haven", "having", "havoc", "he", "head", "heads", "hear", "heard", "heat", "held", "help", "hence", "here", 
"hexadecimal", "hiding", "high", "higher", "highly", "hiker", "him", "his", "historical", "history", "hoc", "hold", 
"holding", "hole", "home", "homework", "hominem", "host", "hot", "hour", "hours", "how", "however", "human", "humans", 
"humongous", "humorous", "humorously", "hundreds", "hung", "hungry", "hungus", "hurry", "hyphen", "hypothetical", 
"hysterical", "i", "idea", "identify", "idiot", "idiots", "if", "ignorant", "ignoring", "illegal", "illegality", 
"illustrate", "images", "imbedded", "immediate", "immediately", "immense", "imminent", "imp", "imper", "implement", 
"implemented", "implementors", "implication", "implicit", "implicitly", "implied", "implies", "imply", "implying", 
"important", "impossibility", "impossible", "impressive", "in", "inanimate", "inarticulations", "inbetween", 
"incapable", "incessantly", "include", "included", "incomplete", "incomprehensible", "incorporated", "incorrect", 
"increase", "incredibly", "incredulity", "increment", "indenting", "independent", "indeterminate", "indicate", 
"indicates", "indication", "indistinguishable", "individual", "industry", "inelegance", "inelegant", "infamous", 
"inference", "inferences", "inferior", "infinite", "infinitely", "influenced", "information", "ing", "inherently", 
"initials", "inner", "input", "inquiry", "inquisitive", "insert", "inserting", "inside", "insignificant", "inspiring", 
"install", "installations", "installed", "installing", "instance", "instantiation", "instead", "institutions", 
"instruction", "instructions", "integers", "intelligent", "intended", "intent", "intention", "interacting", 
"interaction", "interchangeably", "interest", "interface", "interfaces", "interj", "interjection", "interjectively", 
"interminably", "intermittently", "interpretation", "interpreting", "interrupt", "interruption", "intervals", "into", 
"introduced", "intuition", "invalid", "invent", "invented", "inversely", "invoke", "invoked", "involve", "involved", 
"involves", "involving", "irrevocable", "irritation", "is", "isn", "issue", "it", "items", "iterations", "iterative", 
"its", "itself", "jargon", "jay", "jerst", "jest", "jfcl", "jiffy", "job", "jobs", "joke", "jpd", "jrst", "judgment", 
"jump", "junk", "just", "kat", "keep", "keeps", "kept", "keyboard", "keys", "kill", "kind", "kl", "kloodj", "kluge", 
"kluged", "kluges", "knob", "know", "knowledge", "known", "knows", "koe", "kretch", "ku", "kwess", "lack", "language", 
"large", "largely", "larger", "last", "late", "lately", "later", "latest", "latter", "lawyer", "layman", "lays", 
"learn", "learning", "least", "leave", "leaves", "leaving", "leeway", "left", "legal", "length", "less", "lesser", 
"let", "letter", "letters", "letting", "lettuce", "level", "licence", "license", "lid", "lif", "light", "like", "limb", 
"limitations", "limited", "line", "lines", "linguistic", "link", "linked", "linkee", "linker", "linking", "links", 
"lip", "lish", "list", "listener", "listing", "listings", "little", "live", "lives", "ll", "load", "loaders", 
"loading", "lobotomized", "local", "location", "locked", "locker", "log", "logged", "logic", "logical", "login", 
"long", "longer", "look", "looked", "looking", "looks", "loop", "loops", "loosely", "lose", "loser", "losers", "loses", 
"losing", "loss", "lossage", "lossages", "lost", "lot", "loud", "love", "low", "lpt", "lt", "lucky", "lurking", 
"luser", "lusers", "machine", "machines", "made", "magic", "magically", "magnetic", "magnitude", "mail", "main", 
"mainly", "maintained", "make", "makes", "making", "malfunction", "malfunctioning", "malicious", "maliciously", 
"managed", "manifestation", "manipulate", "manipulation", "manner", "manual", "manufacturers", "many", "marginal", 
"marginally", "mark", "marked", "master", "match", "mater", "mathematical", "matrix", "maximum", "may", "maybe", "mc", 
"me", "meal", "mean", "meaning", "meaningless", "meanings", "means", "meant", "measured", "mechanical", "mechanism", 
"meddler", "meet", "megabyte", "megacharacters", "member", "memories", "memory", "mented", "mentions", "mercy", 
"merit", "mess", "message", "messages", "meta", "metaphoric", "metaphorical", "metaphorically", "metasyntactic", 
"method", "methods", "microLenat", "microseconds", "microtapes", "middle", "might", "mild", "milder", "miles", 
"million", "millisecond", "minimum", "minor", "minus", "minutes", "misconceptions", "misfeature", "misfeatures", 
"missing", "mitten", "mixing", "mobies", "moby", "mod", "mode", "model", "modifications", "modified", "module", 
"modulo", "moment", "mon", "money", "monitor", "months", "moon", "more", "most", "mostly", "motivation", "motor", 
"move", "movement", "moving", "much", "mumblage", "mumble", "mumbling", "mun", "munch", "mung", "mungs", "musical", 
"must", "my", "mysteriosity", "mysterious", "mythical", "naive", "name", "named", "names", "nasty", "naturally", 
"nature", "near", "neat", "neatness", "necessarily", "necessary", "necessity", "nee", "need", "needed", "needn", 
"needs", "negative", "negligible", "neither", "net", "network", "never", "nevertheless", "new", "news", "next", "nice", 
"nickname", "night", "nimble", "nitsm", "no", "nobody", "noises", "noisy", "non", "none", "nonetheless", "nonsense", 
"nonuniform", "nor", "normal", "normally", "north", "not", "notably", "notation", "note", "noted", "nothing", "noun", 
"nouns", "novel", "now", "number", "numbers", "numerals", "object", "objections", "objects", "obnoxious", "obscene", 
"obscenities", "obscenity", "obscure", "observation", "obsolete", "obtain", "obtained", "obvious", "obviously", 
"occasional", "occasionally", "occupied", "occur", "ocean", "octal", "octothorp", "of", "off", "official", "often", 
"oh", "okay", "old", "on", "once", "one", "ones", "oneself", "only", "onomatopoeic", "onto", "op", "opcode", "opcodes", 
"open", "opened", "operating", "operation", "operations", "opinion", "opponent", "opposed", "optimal", "options", "or", 
"oral", "orally", "order", "ordinal", "ordinary", "organized", "oriented", "original", "originally", "originated", 
"origins", "oscilloscope", "other", "others", "otherwise", "ought", "out", "output", "outputs", "outputting", 
"outrage", "outside", "over", "overlapping", "overloaded", "overly", "override", "own", "oxen", "oxide", "package", 
"page", "pages", "pain", "painful", "palms", "paper", "papers", "parameter", "parameters", "parenthesis", "parity", 
"parse", "parsed", "parsing", "part", "participates", "particular", "particularly", "party", "pass", "passed", 
"passes", "password", "patch", "patches", "patently", "patterns", "pay", "paying", "pdl", "peanut", "pejorative", 
"pejoratively", "peninsula", "people", "perform", "performing", "performs", "perhaps", "period", "permanently", 
"permission", "permitted", "perpetrated", "perpetrator", "persist", "person", "pertaining", "pessimal", "phantoms", 
"phase", "philosophical", "phrase", "physical", "physically", "physics", "pib", "picked", "picture", "piddle", "piece", 
"pieces", "pip", "pipeline", "pity", "pivoting", "pl", "place", "places", "plan", "plane", "planned", "plate", 
"plates", "play", "playing", "pleasing", "plop", "plural", "plus", "point", "pointed", "pointless", "points", "poking", 
"pole", "pool", "poor", "poorly", "pop", "popj", "popular", "popularized", "porosity", "porous", "portion", "portions", 
"portmanteau", "position", "posses", "possessor", "possibility", "possible", "possibly", "post", "posts", "pound", 
"power", "powered", "powerful", "ppn", "practical", "practiced", "praise", "prank", "preceded", "preceding", 
"precisely", "precision", "predates", "predicate", "pree", "prefaces", "prefer", "preferred", "prefix", "prefixed", 
"prep", "presence", "pretty", "primarily", "primary", "prime", "print", "printed", "printer", "printing", "prints", 
"priority", "privilege", "probability", "probably", "problem", "procedure", "proceed", "proceeding", "process", 
"processes", "processing", "produce", "produced", "produces", "producing", "products", "profound", "program", 
"programmable", "programmed", "programmer", "programmers", "programming", "programs", "progress", "project", 
"prolific", "prominence", "prone", "pronounced", "pronunciation", "proof", "propagate", "proper", "properly", 
"properties", "property", "proportional", "proposed", "protections", "protocol", "protruding", "provided", "provides", 
"providing", "pseudo", "psychedelic", "publicized", "publicly", "published", "puddle", "pull", "pulling", "pun", 
"punch", "punning", "punt", "puppet", "pure", "purely", "purpose", "purposely", "purposes", "purveyors", "push", 
"pushed", "put", "puts", "putting", "qualification", "qualifier", "quality", "quantities", "quantity", "question", 
"questions", "queue", "quick", "quickly", "quite", "quizzical", "quo", "quote", "rabidly", "railroad", "raise", 
"raisins", "ramifications", "random", "randomly", "randomness", "rapidly", "raping", "rare", "rarely", "raster", 
"rather", "ratio", "raving", "ravs", "re", "read", "reading", "reads", "ready", "real", "reality", "really", "reason", 
"reasonable", "reasons", "recall", "recent", "recently", "receptacle", "reclaim", "recognizable", "recognized", 
"record", "recoverable", "recursive", "recycle", "reduce", "reel", "refer", "reference", "referent", "referred", 
"refers", "reflects", "reflexively", "regardless", "regenerated", "registers", "regular", "reign", "related", 
"relatively", "release", "reliability", "reload", "reloaded", "reluctance", "remain", "remark", "remedy", "remember", 
"reminder", "remove", "removed", "removes", "repair", "repeated", "repeatedly", "replaced", "replacement", 
"replicators", "reply", "reported", "represent", "representing", "republished", "request", "requester", "requests", 
"requires", "requiring", "research", "residence", "respect", "respective", "response", "responsible", "restart", 
"restaurant", "restricted", "result", "resulting", "results", "retrying", "return", "returns", "revert", "revolted", 
"rhyming", "ridiculous", "right", "risen", "roman", "room", "rotating", "roughly", "routine", "rubbish", "rule", 
"rules", "run", "running", "runoff", "runs", "sacred", "sagas", "sahss", "said", "sake", "sales", "same", "sample", 
"samples", "sanity", "sarcastic", "satisfactory", "save", "saved", "saving", "saw", "say", "saying", "says", "scale", 
"scanner", "schedule", "scheduled", "scheme", "school", "science", "scraping", "screen", "screw", "screws", "scroll", 
"search", "seat", "second", "secondary", "seconds", "see", "seeing", "seem", "seemingly", "seems", "seen", "semester", 
"semi", "semicolon", "seminar", "send", "sending", "sense", "senses", "sentence", "separable", "sequence", "serial", 
"series", "serious", "server", "service", "session", "set", "sets", "setting", "setup", "seven", "several", "severe", 
"share", "shift", "shir", "shirt", "shit", "shoddy", "shoelaces", "short", "shortened", "should", "shoulders", 
"shouldn", "show", "showing", "shrinking", "sic", "sick", "side", "sided", "sigh", "sign", "signal", "significant", 
"significantly", "silly", "similar", "similarly", "simple", "simpler", "simplify", "simply", "simulated", "simulation", 
"simulations", "simultaneity", "simultaneously", "since", "single", "sink", "sis", "sites", "situation", "six", 
"sixes", "size", "sized", "skig", "slang", "sleep", "sleeping", "sliced", "slide", "slightly", "slip", "slop", 
"slurps", "small", "smaller", "smart", "smeared", "smoke", "snarfed", "so", "soak", "soaking", "soft", "software", 
"softwarily", "softwary", "solid", "solution", "solve", "some", "somebody", "someone", "something", "sometimes", 
"somewhat", "somewhere", "soon", "sort", "sorts", "sound", "sounds", "soup", "soups", "sour", "source", "south", 
"space", "spaces", "spacewar", "spastically", "spawned", "spazz", "spazzes", "spazzing", "speak", "speaker", 
"speaking", "speaks", "special", "specific", "specifically", "specification", "specified", "spectrum", "speech", 
"speeches", "spelled", "spelling", "sphere", "spilled", "spin", "splat", "spoken", "spool", "spooler", "spoolers", 
"spooling", "spoonerism", "sport", "spread", "spreading", "spur", "spy", "sqiggle", "squares", "squiggle", "stack", 
"stalling", "standard", "stands", "star", "start", "starvation", "state", "statistics", "status", "stay", "stemming", 
"stick", "sticking", "still", "stop", "stopped", "stops", "storage", "store", "story", "straightforward", "strangely", 
"street", "stretch", "strictly", "strip", "stripping", "strips", "structure", "structures", "stuck", "student", 
"students", "study", "stuff", "stupid", "sty", "sub", "subject", "subjects", "subroutine", "subsequently", 
"substitute", "substituted", "substituting", "substitution", "subtle", "succeed", "such", "sudden", "suddenly", 
"suffered", "suffering", "suffice", "sufficient", "sufficiently", "suggested", "suggesting", "suitably", "suited", 
"super", "superfluous", "supervision", "supervisor", "supplied", "supply", "support", "sure", "surface", "surprise", 
"surprising", "surrounded", "suspended", "swap", "swapped", "swapper", "swinging", "switch", "switches", "syllable", 
"symbol", "synonym", "synonymously", "synonyms", "syntactic", "syntax", "synthesize", "system", "systems", "tactic", 
"tactics", "tail", "take", "taken", "takes", "taking", "talk", "talked", "talking", "tape", "task", "tasks", "tasty", 
"taxonomy", "tears", "technical", "technique", "tedious", "tee", "teeth", "telephone", "teletype", "tell", 
"temporarily", "temporary", "ten", "tendency", "tends", "tense", "term", "termed", "terminal", "terminals", 
"terminate", "terminology", "terms", "text", "than", "thanks", "that", "the", "their", "them", "themselves", "then", 
"thence", "theoretical", "theorizing", "theory", "there", "thereby", "therefore", "thereof", "these", "thesis", "they", 
"thing", "things", "think", "thinking", "third", "this", "those", "though", "thought", "thrash", "three", "through", 
"throughout", "throw", "thumb", "tick", "tie", "tight", "tightly", "tilde", "time", "times", "timesharing", "tinged", 
"tip", "tired", "title", "titty", "to", "toad", "today", "toe", "together", "toggle", "toggling", "token", "tolerance", 
"tomato", "tomorrow", "tone", "tongue", "tonight", "too", "took", "top", "topic", "total", "touch", "toward", "trace", 
"track", "tradeoff", "transcript", "transfer", "transform", "transitively", "translation", "transmitting", "trap", 
"traps", "tredecimal", "trick", "tried", "tries", "triggered", "trivial", "triviality", "trouble", "true", "trunnion", 
"trying", "tty", "tuning", "tur", "turkey", "turn", "turning", "twaddle", "tweak", "tweaked", "tweaking", "twiddle", 
"twiddled", "twiddling", "two", "txt", "tying", "type", "typed", "types", "typical", "typically", "typing", "typist", 
"uL", "ugly", "uh", "unable", "unaesthetic", "unclear", "uncommon", "under", "undergraduate", "underground", 
"understand", "understood", "underwater", "undiluted", "undirected", "undistinguished", "unexpected", "unexpectedly", 
"unexplainable", "unexplained", "unicorn", "unidentified", "unintended", "uninteresting", "unique", "unit", "universe", 
"university", "unlike", "unlink", "unload", "unmanageable", "unmodifiable", "unnecessary", "unparsed", "unpleasant", 
"unproductive", "unrelated", "unreliability", "unreliable", "unspecified", "until", "unusable", "unused", "unusual", 
"unusually", "unveiled", "unwanted", "unwedge", "unwieldy", "up", "updated", "upon", "us", "usage", "use", "used", 
"useful", "useless", "user", "users", "uses", "using", "usual", "usually", "utility", "utter", "utterance", "uttered", 
"v", "valid", "value", "values", "vanilla", "variable", "variant", "varied", "varies", "variety", "various", 
"variously", "ve", "verb", "verbally", "verbs", "verges", "verse", "version", "versions", "vertical", "very", "via", 
"violently", "virgin", "virtual", "vision", "visual", "vital", "vixen", "vol", "volleyball", "Voltagespike", "vomit", 
"wad", "waiting", "waitress", "waking", "wall", "wallpaper", "want", "wanted", "was", "washed", "waste", "wasting", 
"watering", "way", "ways", "we", "wedged", "wedging", "weird", "well", "went", "were", "west", "what", "whatever", 
"wheel", "wheels", "when", "where", "wherein", "whether", "which", "while", "whistle", "whistles", "who", "whole", 
"whose", "wide", "widget", "wildly", "will", "willfully", "windows", "winner", "winners", "winning", "winnitude", 
"wins", "wire", "with", "within", "without", "wizard", "won", "wonder", "wonton", "word", "words", "work", "working", 
"works", "world", "wormhole", "wormholes", "worry", "worrying", "worse", "worth", "would", "wouldn", "woven", 
"wrapped", "wreak", "wrist", "write", "writing", "written", "wrong", "xgp", "y", "yards", "yeah", "year", "years", 
"yes", "yet", "yields", "you", "young", "your", "yourself", "zero", "zeroed", "zeroes", "zeroing", "zotz");

# pick a random number of lines to create
$lines = rand(50) + 1;

$problem_text = "";
$solution_text = "";

for($n = 0; $n < $lines; $n++)
{
  $w = rand(10) + 1;
  $string = "";

  for($i = 0; $i < $w; $i++)
  {
    $string .= $words[rand($#words)] . " ";
  }
  $problem_text .= "$string\n";
  $solution_text .= "Hello world\n";
}

if($problem_file and $solution_file)
{
  open PROBLEM, ">", $problem_file or die $!;
  print PROBLEM $problem_text;
  close(PROBLEM);

  open SOLUTION, ">", $solution_file or die $!;
  print SOLUTION $solution_text;
  close(SOLUTION);
}
